version: 0.1.1.{build}
pull_requests:
  do_not_increment_build_number: true
environment:
  SonarToken:
    secure: +wTbJz9KGTWgbZs0XwkTvkyHzso0IwglDTd3d4CXC8DYT2B40D4DcjrmeEWDHSeU
branches:
  only:
  - develop
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
- cmd: choco install "msbuild-sonarqube-runner" -y
- cmd: MSBuild.SonarQube.Runner.exe begin /k:"steven-r:Oberon0Compiler" /n:"Oberon 0 Compiler" /v:"{version}" /d:sonar.host.url=https://sonarqube.com /d:sonar.login=%SonarToken%

test_script:
- cmd: nunit3-console "%APPVEYOR_BUILD_FOLDER%\UnitTestProject1\bin\Debug\UnitTestProject1.dll" --result:TestReport.xml;format=nunit2

after_test:
- cmd: MSBuild.SonarQube.Runner.exe end /d:sonar.login=%SonarToken%
