using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;

namespace InternalGenerators;

[Generator]
public class InternalFunctionGenerator : IIncrementalGenerator
{
    internal static readonly string AttributeName = "InternalFunctionAttribute";
    internal static readonly string AttributeFullName = "Oberon0.Compiler.Expressions.Functions.InternalFunctionAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Step 1: Select all class declarations with attributes
        var classDeclarations = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (_, _) => true,
                transform: ParseInternalFunction
            )
            .Where(static symbol => symbol is not null);

        // Step 3: Collect into an array
        var collected = classDeclarations.Collect();

        // Step 4: Generate output
        context.RegisterSourceOutput(collected, static (spc, classes) =>
        {
            var code = GenerateReport(classes!);
            spc.AddSource("InternalFunctionCollection.g.cs", code);
        });
    }

    private List<InternalFunctionSetup> ParseInternalFunction(GeneratorAttributeSyntaxContext ctx, CancellationToken token)
    {
        List<InternalFunctionSetup> functions = [];

        if (ctx.TargetSymbol is not INamedTypeSymbol symbol)
        {
            functions.Add(new InternalFunctionSetup { ErrorMessage = "Cannot map context to INamedTypeSymbol" });
            return functions;
        }

        var classDecl = (ClassDeclarationSyntax)ctx.TargetNode;

        var interfaces = symbol.Interfaces;
        if (interfaces == null)
        {
            functions.Add(new InternalFunctionSetup { ClassName = symbol.Name, ErrorMessage = "Class does not inherit IInternalFunction"});
            return functions;
        }

        var baseType = interfaces.FirstOrDefault(x => x.Name == "IInternalFunction");
        if (baseType == null)
        {
            functions.Add(new InternalFunctionSetup { ClassName = symbol.Name, ErrorMessage = "Class does not inherit IInternalFunction: " + string.Join("\n", interfaces.Select( x => x.Name )) });
            return functions;
        }

        var func = new InternalFunctionSetup
        {
            NameSpace = symbol.ContainingNamespace.ToDisplayString(),
            ClassName = symbol.Name,
        };
        functions.Add(func);
        return functions;
    }

    private static string GenerateReport(IReadOnlyList<List<InternalFunctionSetup>> intFunctions)
    {
        var spaces = "            ";
        var internalFunctions = intFunctions.SelectMany(fun => fun); // flatten

        var sb = new System.Text.StringBuilder();
        sb.AppendLine($@"// <auto-generated/>
namespace Oberon0.Compiler.Expressions;

using System;
using System.Collections.Generic;

using Oberon0.Compiler.Expressions.Functions;

internal partial class ExpressionRepository
{{
    internal static partial List<IInternalFunction> GetSupportedFunctions()
    {{
        return new List<IInternalFunction>
        {{");
        foreach (var func in internalFunctions)
        {
            if (func.ErrorMessage != null)
            {
                sb.AppendLine(spaces + "// " + func.ErrorMessage);
                continue;
            }
            sb.AppendLine(spaces + $"new {func.NameSpace ?? "---"}.{func.ClassName ?? "---"}(),");
        }
        sb.AppendLine(@"        };
    }
}");
        return sb.ToString();
    }

}

