using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;

namespace InternalGenerators;

[Generator]
public class OperatorGenerator : IIncrementalGenerator
{
    internal static readonly string AttributeName = "ArithmeticOperation";
    internal static readonly string AttributeClassName = "ArithmeticOperationAttribute";
    internal static readonly string AttributeFullName = "Oberon0.Compiler.Expressions.Operations.Internal.ArithmeticOperationAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Step 1: Select all class declarations with attributes
        var classDeclarations = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (_, _) => true,
                transform: ParseArithmeticAttribute
            )
            .Where(static symbol => symbol is not null);

        // Step 3: Collect into an array
        var collected = classDeclarations.Collect();

        // Step 4: Generate output
        context.RegisterSourceOutput(collected, static (spc, classes) =>
        {
            var code = GenerateReport(classes!);
            spc.AddSource("OperatorCollection.g.cs", code);
        });
    }

    private List<ArithmeticOperation> ParseArithmeticAttribute(GeneratorAttributeSyntaxContext ctx, CancellationToken token)
    {
        List<ArithmeticOperation> ops = [];
        if (ctx.TargetSymbol is not INamedTypeSymbol classSymbol)
        {
            ops.Add(new ArithmeticOperation { ErrorMessage = "Cannot map context to INamedTypeSymbol" });
            return ops;
        }

        foreach (var attr in classSymbol.GetAttributes())
        {
            if (attr == null || !(attr.AttributeClass?.Name == AttributeClassName))
            {
                continue; // skip other attributes
            }
            if (attr.ConstructorArguments.Count() != 4)
            {
                ops.Add(new ArithmeticOperation { ClassRef = classSymbol, ErrorMessage = "Number of arguments must be 4" });
                continue; 
            }
            var op = new ArithmeticOperation
            {
                ClassRef = classSymbol,
                Operation = attr.ConstructorArguments[0],
                Left = attr.ConstructorArguments[1],
                Right = attr.ConstructorArguments[2],
                ResultType = attr.ConstructorArguments[3]
            };
            ops.Add(op);
        }
        return ops;
    }

    private static string GenerateReport(IReadOnlyList<List<ArithmeticOperation>> opsList)
    {
        var spaces = "            ";
        var ops = opsList.SelectMany(op => op); // flatten

        var sb = new System.Text.StringBuilder();
        sb.AppendLine($@"// <auto-generated/>
namespace Oberon0.Compiler.Expressions;

using System;
using System.Collections.Generic;

using Oberon0.Compiler.Expressions.Operations.Internal;

internal partial class ExpressionRepository
{{
    internal static partial List<ArithmeticOpKey> GetSupportedOperations()
    {{
        return new List<ArithmeticOpKey>
        {{");
        foreach (var op in ops)
        {
            if (op.ErrorMessage != null)
            {
                sb.AppendLine(spaces + "// " + op.ErrorMessage);
                continue;
            }
            try
            {
                sb.AppendLine(
                    spaces +
                    $"new ArithmeticOpKey({op.Operation.ToCSharpString()}, " +
                    $"{op.Left.ToCSharpString()}, " +
                    $"{op.Right.ToCSharpString()}, " +
                    $"{op.ResultType.ToCSharpString()}, " +
                    $"new {op.ClassRef!.ContainingNamespace.ToDisplayString()}.{op.ClassRef!.Name}()),");
            }
            catch (Exception ex)
            {
                sb.AppendLine("// Error: " + ex.Message);
                continue;
            }
        }
        sb.AppendLine(spaces + @"};
    }
}");
        return sb.ToString();
    }

}

internal class ArithmeticOperation
{
    public TypedConstant Operation { get; set; }

    public TypedConstant Left { get; set; }

    public TypedConstant Right { get; set; }

    public TypedConstant ResultType { get; set; }

    public INamedTypeSymbol? ClassRef { get; internal set; }

    public string? ErrorMessage { get; set; }
}

