<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Configurations>Debug;Release;Test</Configurations>
    <Nullable>enable</Nullable>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Antlr4.Runtime.Standard" Version="4.13.1" />
    <PackageReference Include="Antlr4BuildTasks" Version="12.14.0" />
    <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" />
    <PackageReference Include="xunit" Version="2.9.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\oberon0\Oberon0Compiler.csproj" />
  </ItemGroup>
</Project>