<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Oberon0.Generator.LLVM</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LLVMSharp" Version="20.1.2" />
    <PackageReference Include="LLVMSharp.Interop" Version="20.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Oberon0.System\Oberon0.System.csproj" />
    <ProjectReference Include="..\oberon0\Oberon0Compiler.csproj" />
  </ItemGroup>

</Project>