name: .NET CI

on:
 push:
 workflow_dispatch:
 pull_request:
   types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install dotnet tools
      run: |
        dotnet tool install --global dotnet-sonarscanner
        dotnet tool install --global dotnet-coverage

    - name: Begin analysis on SonarCloud
      run: |
        dotnet sonarscanner begin /k:"steven-r_Oberon0Compiler" /o:"steven-r-github" /d:sonar.branch.name=$BRANCH_NAME /d:sonar.host.url="https://sonarcloud.io" /d:sonar.token=${{ secrets.SONAR_SECRET }} /d:sonar.pullrequest.provider=github /d:sonar.dotnet.excludeTestProjects=true /d:sonar.cs.vscoveragexml.reportsPaths=**/dynamic-coverage-*.xml /d:sonar.verbose=true
              
    - name: Build
      run: dotnet build

    - name: Run Tests (with Coverage)
      run: |
        dotnet-coverage collect 'dotnet test --no-build --verbosity normal' -f xml -o dynamic-coverage-std.xml
        
    - name: End analysis on SonarCloud
      run: |
        dotnet sonarscanner end /d:sonar.token=${{ secrets.SONAR_SECRET }}
